baseurl: '/'
languageCode: en-us
theme: hugo-theme-terminal
paginate: 5
params:
  centerTheme: yes
  contentTypeName: posts
  fullWidthTheme: no
  showMenuItems: 5
  themeColor: orange
languages:
  en:
    copyright: ''
    keywords: ''
    menu:
      main:
        - identifier: about
          name: /about
          url: /about
        - identifier: cv
          name: /cv
          url: /cv
        - identifier: posts
          name: /posts
          url: /posts
        - identifier: music
          name: /music
          url: /music
    menuMore: Show more
    params:
      logo:
        logoHomeLink: /
        logoText: Pablo I. Picazo
    readMore: Read more
    readOtherPosts: Read other posts
    subtitle: Personal website
    title: Terminal
